export enum NotificationType {
  USER_REGISTRATION = 'USER_REGISTRATION',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  NEW_MESSAGE = 'NEW_MESSAGE',
  SECURITY_ALERT = 'SECURITY_ALERT',
  ORDER_UPDATE = 'ORDER_UPDATE',
}
